### PR TITLE
Figma API refactor and added types for each element

### PR DESCRIPTION
**Pull request by saur0x**
### Changes
- Migrated the path handling from `os.path` module to the more modern `pathlib` module.
- Removed `*` import from `gui.py`.
- Separated out Figma components from the core designer into a sub-package `figma`.
    - Added `endpoints.py` module to handle the file and image requests from Figma API.
    - Created different classes for each element type specified in the Figma API.
    - Each designer element now has a `to_code` method that returns the generated code.
- Simplified the `-f | --force`  option in `cli.py` to not delete the existing directory.
- Added an image downloader function to `utils.py`.
- Added a core `designer.py` module to handle the design and file write processes.

### Notes
- Tested and working on Windows, Mac and Linux.

### CODE REVIEW

**Comment by ParthJadhav** [comment]
Hey @jrobchin  I have tested and reviewed this PR and this would solve all the issues along with pep-8 refactoring and some more good changes. I request you to merge this PR and I guess this merge would reflect on the Original PR you created on the main repository.

**Comment by ParthJadhav** [comment]
Or you can provide me write access to this repo so I can resolve the conflicts and merge this PR.

**Comment by jrobchin** [comment]
I don't mind merging but there are some conflicts with master.

**Comment by jrobchin** [comment]
Looks great by the way!

**Comment by jrobchin** [comment]
> ... I guess this merge would reflect on the Original PR you created on the main repository.

@ParthJadhav Yeah that's how it works.

**Comment by ParthJadhav** [comment]
> I don't mind merging but there are some conflicts with master.

That's the thing, I can resolve and merge the changes if you provide me with write permissions.

**Comment by jrobchin** [comment]
Conflicts should be fixed on @saur0x 's branch. I'll give you permissions regardless.

**Comment by jrobchin** [comment]
I've invited you both as collaborators.

**Comment by saur0x** [comment]
~~I will leave that to @ParthJadhav as I have no experience with resolving conflicts, and that page looks rather scary.~~
Never mind, that was simple.

**Comment by ParthJadhav** [comment]
Thanks @jrobchin & @saur0x . Awesome work you guys.

**Pull request merged**
